// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/blogs/:blogHandle/:articleHandle": {
    params: {
      "blogHandle": string;
      "articleHandle": string;
    };
  };
  "/sitemap/:type/:page.xml": {
    params: {
      "type": string;
      "page": string;
    };
  };
  "/blogs/:blogHandle": {
    params: {
      "blogHandle": string;
    };
  };
  "/collections/:handle": {
    params: {
      "handle": string;
    };
  };
  "/collections": {
    params: {};
  };
  "/policies/:handle": {
    params: {
      "handle": string;
    };
  };
  "/products/:handle": {
    params: {
      "handle": string;
    };
  };
  "/collections/all": {
    params: {};
  };
  "/policies": {
    params: {};
  };
  "/products": {
    params: {};
  };
  "/sitemap.xml": {
    params: {};
  };
  "/pages/:handle": {
    params: {
      "handle": string;
    };
  };
  "/robots.txt": {
    params: {};
  };
  "/blogs": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
  "/graphiql": {
    params: {};
  };
  "/subrequest-profiler": {
    params: {};
  };
  "/.well-known/appspecific/com.chrome.devtools.json": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/blogs/:blogHandle/:articleHandle" | "/sitemap/:type/:page.xml" | "/blogs/:blogHandle" | "/collections/:handle" | "/collections" | "/policies/:handle" | "/products/:handle" | "/collections/all" | "/policies" | "/products" | "/sitemap.xml" | "/pages/:handle" | "/robots.txt" | "/blogs" | "/contact" | "/about" | "/*" | "/graphiql" | "/subrequest-profiler" | "/.well-known/appspecific/com.chrome.devtools.json";
  };
  "routes/blogs.$blogHandle.$articleHandle.tsx": {
    id: "routes/blogs.$blogHandle.$articleHandle";
    page: "/blogs/:blogHandle/:articleHandle";
  };
  "routes/sitemap.$type.$page[.xml].tsx": {
    id: "routes/sitemap.$type.$page[.xml]";
    page: "/sitemap/:type/:page.xml";
  };
  "routes/blogs.$blogHandle._index.tsx": {
    id: "routes/blogs.$blogHandle._index";
    page: "/blogs/:blogHandle";
  };
  "routes/collections.$handle.tsx": {
    id: "routes/collections.$handle";
    page: "/collections/:handle";
  };
  "routes/collections._index.tsx": {
    id: "routes/collections._index";
    page: "/collections";
  };
  "routes/policies.$handle.tsx": {
    id: "routes/policies.$handle";
    page: "/policies/:handle";
  };
  "routes/products.$handle.tsx": {
    id: "routes/products.$handle";
    page: "/products/:handle";
  };
  "routes/collections.all.tsx": {
    id: "routes/collections.all";
    page: "/collections/all";
  };
  "routes/policies._index.tsx": {
    id: "routes/policies._index";
    page: "/policies";
  };
  "routes/products._index.tsx": {
    id: "routes/products._index";
    page: "/products";
  };
  "routes/[sitemap.xml].tsx": {
    id: "routes/[sitemap.xml]";
    page: "/sitemap.xml";
  };
  "routes/pages.$handle.tsx": {
    id: "routes/pages.$handle";
    page: "/pages/:handle";
  };
  "routes/[robots.txt].tsx": {
    id: "routes/[robots.txt]";
    page: "/robots.txt";
  };
  "routes/blogs._index.tsx": {
    id: "routes/blogs._index";
    page: "/blogs";
  };
  "routes/contact.tsx": {
    id: "routes/contact";
    page: "/contact";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
  "../node_modules/@shopify/hydrogen/dist/vite/virtual-routes/layout.jsx": {
    id: "/Users/jiate/Desktop/shopify/node_modules/@shopify/hydrogen/dist/vite/virtual-routes/layout";
    page: "/graphiql" | "/subrequest-profiler" | "/.well-known/appspecific/com.chrome.devtools.json" | "/";
  };
  "../node_modules/@shopify/hydrogen/dist/vite/virtual-routes/routes/graphiql.jsx": {
    id: "vite/virtual-routes/routes/graphiql";
    page: "/graphiql";
  };
  "../node_modules/@shopify/hydrogen/dist/vite/virtual-routes/routes/subrequest-profiler.jsx": {
    id: "vite/virtual-routes/routes/subrequest-profiler";
    page: "/subrequest-profiler";
  };
  "../node_modules/@shopify/hydrogen/dist/vite/virtual-routes/routes/[.]well-known.appspecific.com[.]chrome[.]devtools[.]json.jsx": {
    id: "vite/virtual-routes/routes/[.]well-known.appspecific.com[.]chrome[.]devtools[.]json";
    page: "/.well-known/appspecific/com.chrome.devtools.json";
  };
  "../node_modules/@shopify/hydrogen/dist/vite/virtual-routes/routes/index.jsx": {
    id: "vite/virtual-routes/routes/index";
    page: "/";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/blogs.$blogHandle.$articleHandle": typeof import("./app/routes/blogs.$blogHandle.$articleHandle.tsx");
  "routes/sitemap.$type.$page[.xml]": typeof import("./app/routes/sitemap.$type.$page[.xml].tsx");
  "routes/blogs.$blogHandle._index": typeof import("./app/routes/blogs.$blogHandle._index.tsx");
  "routes/collections.$handle": typeof import("./app/routes/collections.$handle.tsx");
  "routes/collections._index": typeof import("./app/routes/collections._index.tsx");
  "routes/policies.$handle": typeof import("./app/routes/policies.$handle.tsx");
  "routes/products.$handle": typeof import("./app/routes/products.$handle.tsx");
  "routes/collections.all": typeof import("./app/routes/collections.all.tsx");
  "routes/policies._index": typeof import("./app/routes/policies._index.tsx");
  "routes/products._index": typeof import("./app/routes/products._index.tsx");
  "routes/[sitemap.xml]": typeof import("./app/routes/[sitemap.xml].tsx");
  "routes/pages.$handle": typeof import("./app/routes/pages.$handle.tsx");
  "routes/[robots.txt]": typeof import("./app/routes/[robots.txt].tsx");
  "routes/blogs._index": typeof import("./app/routes/blogs._index.tsx");
  "routes/contact": typeof import("./app/routes/contact.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/about": typeof import("./app/routes/about.tsx");
  "routes/$": typeof import("./app/routes/$.tsx");
  "/Users/jiate/Desktop/shopify/node_modules/@shopify/hydrogen/dist/vite/virtual-routes/layout": unknown;
  "vite/virtual-routes/routes/graphiql": unknown;
  "vite/virtual-routes/routes/subrequest-profiler": unknown;
  "vite/virtual-routes/routes/[.]well-known.appspecific.com[.]chrome[.]devtools[.]json": unknown;
  "vite/virtual-routes/routes/index": unknown;
};